name: CI

on: [push, pull_request]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate
        uses: docker://registry.gitlab.com/professor-rvenson/backend-n1-validate
        with:
          args: validate
